version: "3.5"

services:
  db:
    image: postgres
    restart: always
    container_name: fastbar-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - fastbar-network

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: fastbar-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
    networks:
      - fastbar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.dockerfile
    container_name: fastbar-frontend
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - fastbar-network

networks:
  fastbar-network:
    driver: bridge
