name: Lint

on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install modules
        working-directory: backend
        run: yarn
      - name: Run ESLint
        working-directory: backend
        run: eslint . --ext .js,.jsx,.ts,.tsx
